name: iut_mobile_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.18+61

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # code
  dio: ^5.8.0+1
  intl: ^0.19.0
  dartz: ^0.10.1
  retrofit: ^4.4.1
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.3.0

  # core
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.2.2
  flutter_tts: ^4.2.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2
  flutter_launcher_icons: ^0.14.3
  latlong2: ^0.9.1
  pretty_dio_logger: ^1.4.0
  just_audio: ^0.9.46
  device_info_plus: ^11.3.3
  web_socket_channel: ^3.0.2
  flutter_cache_manager: ^3.4.1
  device_preview:

  # ui
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  percent_indicator: ^4.2.4
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.17
  toastification: ^2.1.0
  flutter_map: ^8.0.0
  skeletonizer: ^1.4.3
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1
  flutter_highlight: ^0.7.0
  flutter_heatmap_calendar: ^1.0.5
  video_player: ^2.9.3
  chewie: ^1.10.0
  confetti: ^0.8.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  implicitly_animated_list: ^2.3.0
  animated_flip_counter: ^0.3.4
  animation_list: ^3.1.0
  flutter_typeahead: ^5.2.0
  searchfield: ^1.2.6

  # models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  faker: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/brand/
    - assets/sounds/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/oswald/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/oswald/Oswald-SemiBold.ttf
          weight: 600
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/source_code_pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/source_code_pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_code_pro/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Italic.ttf
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_code_pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/source_code_pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_code_pro/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_code_pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic


flutter_icons:
  android: true
  ios: true
  image_path: "assets/brand/logo.jpg"
  adaptive_icon_background: "#FFFFFF"



